<?php
/**
 * @var \Mageplaza\HelloWorld\Block\Display $block
 */
?>
<div class="payment-content--ezdefi">
    <div class="ezdefi-payment__value">
        <span class="ezdefi-payment__origin-value--ezdefi"><?php echo $block->getOriginValue(); ?></span> <span> <?php echo $block->getOriginCurrency(); ?> </span>
        <span class="ezdefi-payment__icon-convert"><i class="fa fa-retweet" aria-hidden="true"></i></span>
        <span class="ezdefi-payment__currency-value--ezdefi"><?php echo $block->getCryptoValue()?></span> <span class="ezdefi-payment__currency--ezdefi"><?php echo $block->getCryptoCurrency(); ?></span>
    </div>
    <div class="ezdefi-payment__countdown-box">
        <input type="hidden" id="ezdefi__payment-expiration--ezdefi" value="<?php echo $block->getExpiration() ?>">
        <p>you have <span class="text-red text-bold" id="ezdefi__countdown-label--ezdefi"></span> to scan this QRcode</p>
    </div>
    <div class="qrcode-box">
        <a href="" class="ezdefi-payment__deeplink" target="_blank">
            <img src="<?php echo $block->getQrCode() ?>" alt="" class="ezdefi-payment__qr-code ezdefi-payment__qr-code--ezdefi">
            <p>Scan QR Code or Click to pay</p>
        </a>
        <div class="timeout-notification timeout-notification--ezdefi reload-payment" data-suffixes="--ezdefi">
            <p>{{ payment_time_out }}</p>
        </div>
    </div>
    <div class="ezdefi-payment__download-link">
        <a href="{{ link_download_app_ios }}" target="_blank"><span><i class="fa fa-apple ezdefi-icon-apple"></i></span> Download ezDeFi for IOS </a>
        <a href="{{ link_download_app_android }}" target="_blank"><span><i class="fa fa-android ezdefi-icon-android"></i></span>  Download ezDeFi for Android </a>
    </div>
</div>
<!--<div class="payment-error--ezdefi">-->
<!--    {{ error_cant_create_payment }}-->
<!--</div>-->