<?php
/**
 * @var \Mageplaza\HelloWorld\Block\Display $block
 */
?>
<?php if(!$block->isError()): ?>
<div class="payment-content--ezdefi">
    <div class="ezdefi-payment__value">
        <span class="ezdefi-payment__origin-value--ezdefi"><?php echo $block->getOriginValue(); ?></span>
        <span class="text-uppercase"> <?php echo $block->getOriginCurrency(); ?> </span>
        <span><img src="<?php echo $this->getViewFileUrl('Ezdefi_Payment/image/swap-icon.png'); ?>" alt="" class="ezdefi-payment__icon-convert"></span>
        <span class="ezdefi-payment__currency-value--ezdefi"><?php echo $block->getCryptoValue(); ?></span>
        <span class="text-uppercase"><?php echo $block->getCryptoCurrency(); ?></span>
    </div>
    <div class="ezdefi-payment__countdown-box">
        <input type="hidden" id="ezdefi__payment-expiration--ezdefi" value="<?php echo $block->getExpiration() ?>">
        <p>You have <span class="text-red text-bold" id="ezdefi__countdown-label--ezdefi"></span> to scan this QRcode</p>
    </div>
    <div class="qrcode-box">
        <a href="<?php echo 'ezdefi://'.$this->getDeepLink() ?>" class="ezdefi-payment__deeplink" target="_blank">
            <img src="<?php echo $block->getQrCode() ?>" alt="" class="ezdefi-payment__qr-code ezdefi-payment__qr-code--ezdefi">
            <p class="margin-none">Scan QR Code or Click to pay</p>
        </a>
        <div class="timeout-notification timeout-notification--ezdefi reload-payment" data-suffixes="--ezdefi">
            <p>Time out <br> Click to recreate payment</p>
        </div>
    </div>
    <div class="ezdefi-payment__download-link">
        <a href="https://ezdefi.com/ios" target="_blank"><img src="<?php echo $this->getViewFileUrl('Ezdefi_Payment/image/ios-icon.png'); ?>" alt=""></a>
        <a href="https://ezdefi.com/android" target="_blank"><img src="<?php echo $this->getViewFileUrl('Ezdefi_Payment/image/android-icon.png'); ?>" alt=""></a>
    </div>
</div>
<?php endif; ?>
<?php if($this->isError()): ?>
    <div class="payment-error--simple">
        <?php echo __('Can\'t create payment. Please contact with shop owner.'); ?>
    </div>
<?php endif; ?>
<!--<div class="payment-error--ezdefi">-->
<!--    {{ error_cant_create_payment }}-->
<!--</div>-->