<?php
/**
 * @var \Mageplaza\HelloWorld\Block\Display $block
 */
?>
<div class="payment-content--simple">
    <input type="radio" name="choose-simple-method-qrcode-input" class="hidden" id="choose-full-qrcode-radio" checked>
    <input type="radio" name="choose-simple-method-qrcode-input" class="hidden" id="choose-alternative-qrcode-radio">

    <div class="ezdefi__alert-copy-address">

        <strong>Success!</strong> Amount was copied to the clipboard.
    </div>
    <div class="ezdefi__alert-copy-amount">
        <strong>Success</strong> Address was copied to the clipboard.

    </div>
    <div class="ezdefi-payment__value">
        <span class="ezdefi-payment__origin-value--simple"><?php echo $block->getOriginValue(); ?></span>
        <span data-bind="text: simplePayment.originCurrency"><?php echo $block->getOriginCurrency(); ?></span>
        <span class="ezdefi-payment__icon-convert"><i class="fa fa-retweet" aria-hidden="true"></i></span>
        <span class="ezdefi-payment__currency-value--simple" data-bind="text: simplePayment.value"><?php echo $block->getCryptoValue(); ?></span>
        <span class="ezdefi-payment__currency--simple" data-bind="text: simplePayment.currency"><?php echo $block->getCryptoCurrency(); ?></span>
    </div>
    <div class="ezdefi-payment__countdown-box">
        <input type="hidden" id="ezdefi__payment-expiration--simple" value="<?php echo $block->getExpiration() ?>">
        <p>you have <span class="text-red text-bold" id="ezdefi__countdown-label--simple"></span> to scan this QRcode</p>
    </div>

    <div class="simple-method-with-full-qrcode">
        <div class="qrcode-box">
            <a href="" target="_blank" class="ezdefi-payment__deeplink ezdefi-payment__deeplink--simple">
                <img src="<?php echo $block->getGatewayQrCode(); ?>" alt="" class="ezdefi-payment__qr-code--simple">
                <p class="margin-none">Scan QR Code or Click to pay</p>
            </a>
            <div class="timeout-notification timeout-notification--simple reload-payment" data-suffixes="--simple">
                <p>{{ payment_time_out }}</p>
            </div>
        </div>
        <p class="margin-top-md text-red">If you get error when scanning this QR Code, please use
            <label class="label-radio-button" for="choose-alternative-qrcode-radio"> alternative QR Code </label>
        </p>
    </div>
    <div class="simple-method-with-alternative-qrcode">
        <div class="qrcode-box">
            <a href="" target="_blank" class="ezdefi-payment__deeplink ezdefi-payment__deeplink--simple">
                <img src="https://chart.googleapis.com/chart?cht=qr&chl=<?php echo $block->getWalletAddress(); ?>&chs=200x200&chld=L|0" alt="" class="ezdefi-payment__qr-code--simple">
                <p class="margin-none">Scan QR Code or Click to pay</p>
            </a>
            <div class="timeout-notification timeout-notification--simple reload-payment" data-suffixes="--simple">
                <p>{{ payment_time_out }}</p>
            </div>
        </div>
        <p class="margin-none"><b>Address:</b> <span class="ezdefi__simple-wallet-address"><?php echo $block->getWalletAddress() ?></span>
            <span class="btn-copy-address"><img src="<?php echo $this->getViewFileUrl('Ezdefi_Payment/image/icon-copy.png'); ?>" alt=""></span>
        </p>
        <p><b>Amount:</b> <span class="ezdefi__simple-amount"></span><span class="ezdefi-payment__currency--simple"><?php echo $block->getCryptoValue() ?></span>
            <span class="btn-copy-amount"><img src="<?php echo $this->getViewFileUrl('Ezdefi_Payment/image/icon-copy.png'); ?>" alt=""></span>
        </p>
        <p class="margin-top-md text-red">You have to pay exact amount so that your order can be handled properly. <br>
            If you have difficulty for sending exact amount try to use <label for="ezdefi-show-payment--ezdefi" class="link_use_ezdefi_wallet"><i>ezDeFi Wallet.</i></label></p>
        <label class="label-radio-button" for="choose-full-qrcode-radio">Use previous QR Code</label>
    </div>
</div>
<div class="payment-error--simple">
    {{ error_cant_create_amount }}
</div>

<script>
    require([
        'jquery',
    ], function ($) {
        $(function () {
            $(document).on("click", ".btn-copy-address", function () {
                copytext(".ezdefi__simple-wallet-address");
                $(".ezdefi__alert-copy-address").show(500, function () {
                    $(".ezdefi__alert-copy-address").delay(1500).hide(500);
                })
            });

            $(".btn-copy-amount").click(function () {
                copytext(".ezdefi__simple-amount");
                $(".ezdefi__alert-copy-amount").show(500, function () {
                    $(".ezdefi__alert-copy-amount").delay(1500).hide(500);
                })
            });

            var copytext = function (elementToCopy) {
                let text = $(elementToCopy).html();
                let tmpElem = document.createElement("input");
                document.body.appendChild(tmpElem);
                tmpElem.value = text;
                tmpElem.select();
                document.execCommand("copy");
                document.body.removeChild(tmpElem);
            };
        });
    });
</script>