<?php
/**
 * @var \Mageplaza\HelloWorld\Block\Display $block
 */
?>

<?php if(!$block->isError()): ?>
<div class="payment-content--simple" data-bind="style:{'display': 'none'}">
    <input type="radio" name="choose-simple-method-qrcode-input" class="hidden" id="choose-full-qrcode-radio" checked>
    <input type="radio" name="choose-simple-method-qrcode-input" class="hidden" id="choose-alternative-qrcode-radio">
    <p><?php echo $block->getPaymentId(); ?></p>
    <div class="ezdefi__alert-copy-address">
        <strong>Success</strong> Address was copied to the clipboard.
    </div>
    <div class="ezdefi__alert-copy-amount">
        <strong>Success!</strong> Amount was copied to the clipboard.
    </div>
    <div class="ezdefi-payment__value">
        <span class="ezdefi__payment--origin-value">
            <span><?php echo $block->getOriginValue(); ?></span>
            <span class="text-uppercase"><?php echo $block->getOriginCurrency(); ?></span>
        </span>
        <span><img src="<?php echo $this->getViewFileUrl('Ezdefi_Payment/image/swap-icon.png'); ?>" alt="" class="ezdefi-payment__icon-convert"></span>
        <span class="ezdefi__payment--crypto-value">
            <span><?php echo $block->getCryptoValue(); ?></span>
            <span class="text-uppercase"><?php echo $block->getCryptoCurrency(); ?></span>
        </span>
    </div>
    <div class="ezdefi-payment__countdown-box">
        <input type="hidden" id="ezdefi__payment-expiration--simple" value="<?php echo $block->getExpiration() ?>">
        <p>you have <span class="text-red text-bold" id="ezdefi__countdown-label--simple"></span> to scan this QRcode</p>
    </div>

    <div class="qrcode-box simple-method-with-full-qrcode">
        <a href="" target="_blank" class="ezdefi-payment__deeplink ezdefi-payment__deeplink--simple">
            <img src="<?php echo $block->getGatewayQrCode(); ?>" alt="" class="ezdefi-payment__qr-code--simple">
            <p class="margin-none">Scan QR Code or Click to pay</p>
        </a>
        <div class="timeout-notification timeout-notification--simple reload-payment" data-suffixes="--simple">
            <p>Time out <br> Click to recreate payment</p>
        </div>
    </div>
    <div class="qrcode-box simple-method-with-alternative-qrcode">
        <a href="" target="_blank" class="ezdefi-payment__deeplink ezdefi-payment__deeplink--simple">
            <img src="https://chart.googleapis.com/chart?cht=qr&chl=<?php echo $block->getWalletAddress(); ?>&chs=200x200&chld=L|0" alt="" class="ezdefi-payment__qr-code--simple">
            <p class="margin-none">Scan QR Code or Click to pay</p>
        </a>
        <div class="timeout-notification timeout-notification--simple reload-payment" data-suffixes="--simple">
            <p>Time out <br> Click to recreate payment</p>
        </div>
    </div>

    <p class="margin-bottom-sm">
        <b>Address:</b>
        <span class="btn-copy-address">
            <span class="ezdefi__simple-wallet-address"><?php echo $block->getWalletAddress() ?></span>
            <span><img src="<?php echo $this->getViewFileUrl('Ezdefi_Payment/image/icon-copy.png'); ?>" alt=""></span>
        </span>
    </p>
    <p>
        <b>Amount:</b>
        <span class="btn-copy-amount">
            <span class="ezdefi__simple-amount"><?php echo $block->getCryptoValue() ?></span>
            <span class="copy-address-icon"><img src="<?php echo $this->getViewFileUrl('Ezdefi_Payment/image/icon-copy.png'); ?>" alt=""></span>
        </span>
    </p>
    <p class="margin-top-md text-red simple-method-with-full-qrcode">If you get error when scanning this QR Code, please use
        <label class="label-radio-button" for="choose-alternative-qrcode-radio"> alternative QR Code </label>
    </p>

    <p class="margin-top-md text-red simple-method-with-alternative-qrcode">
        You have to pay exact amount so that your order can be handled properly. <br>
        If you have difficulty for sending exact amount try to use
        <label class="link_use_ezdefi_wallet" for="choose-simple-ezdefi-radio">
            <i>ezDeFi Wallet.</i>
        </label>
    </p>
    <label class="label-radio-button simple-method-with-alternative-qrcode" for="choose-full-qrcode-radio">Use previous QR Code</label>
</div>
<?php endif; ?>
<?php if($this->isError()): ?>
<div class="payment-error--simple">
    Can not generate amountID
</div>
<?php endif; ?>

<script>
    require([
        'jquery',
    ], function ($) {
        $(function () {
            $(document).on("click", ".btn-copy-address", function () {
                copytext(".ezdefi__simple-wallet-address");
                $(".ezdefi__alert-copy-address").show(500, function () {
                    $(".ezdefi__alert-copy-address").delay(1500).hide(500);
                })
            });

            $(".btn-copy-amount").click(function () {
                copytext(".ezdefi__simple-amount");
                $(".ezdefi__alert-copy-amount").show(500, function () {
                    $(".ezdefi__alert-copy-amount").delay(1500).hide(500);
                })
            });

            var copytext = function (elementToCopy) {
                let text = $(elementToCopy).html();
                let tmpElem = document.createElement("input");
                document.body.appendChild(tmpElem);
                tmpElem.value = text;
                tmpElem.select();
                document.execCommand("copy");
                document.body.removeChild(tmpElem);
            };
        });
    });
</script>